import './isolated-network-guard.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {processArrival,createArrivalRepository,validatePhoto,customerContactVersion,packageReviewVersion} from '../backend/arrival-workflow.mjs';

// A real JPEG fixture; only synthetic identities and reserved example.test addresses.
const image=fs.readFileSync(new URL('../../parcel-snap-vision-test/fixtures/synthetic-label-unmarked.jpg',import.meta.url));
const dataUrl='data:image/jpeg;base64,'+image.toString('base64');
const id=n=>String(n).padStart(8,'0')+'-1111-4111-8111-111111111111';
const contactVersion=await customerContactVersion(id(1),{id:id(2),contact_revision:'seed-1'});
const correctedContactVersion=await customerContactVersion(id(1),{id:id(22),contact_revision:'seed-1'});
const ids={company:id(1),customer:id(2),origin:id(3),destination:id(4),package:id(5),user:id(6)};
const copy=v=>structuredClone(v);

function harness(){
 const state={packages:[],photos:[],notices:[],events:[],legacy:[],customers:[{id:ids.customer,company_id:ids.company,name:'Synthetic Recipient',email:'recipient@example.test',contact_revision:'seed-1'}],facilities:[{id:ids.origin,company_id:ids.company,name:'Origin',city:'Test City',active:true},{id:ids.destination,company_id:ids.company,name:'Destination',city:'Other City',active:true}],profile:{needs_customer_notifications:true,notification_channels:['EMAIL']}};
 const flags={schema:true,privateBucket:true,uploadError:false,downloadError:false,corruptDownload:false,photoOwnership:true,allowOperate:true,secret:true,providerStatus:200,providerThrow:false,malformed:false,finishFailures:0,prepareFailure:false,providerDelay:0};
 const objects=new Map(),calls=[],queries=[];let sequence=100,queue=Promise.resolve();
 const row=x=>x?[copy(x)]:[];
 async function unsafe(query,p=[]){
  queries.push({query,p:copy(p)});const q=query.toLowerCase();
  if(q.includes('to_regclass'))return [{ready:flags.schema}];
  if(q.includes('pg_advisory_xact_lock'))return [{}];
  if(q.startsWith('select exists(select 1 from parcel_snap.package_photos'))return [{seen:state.photos.some(x=>x.company_id===p[0]&&x.package_id===p[1]&&x.facility_id===p[2]&&x.kind==='DESTINATION')||state.events.some(x=>x[0]===p[1]&&x[1]==='DESTINATION_RECEIVED'&&[p[3],p[4]].includes(x[2]))}];
  if(q.startsWith('select n.id')){
   const n=state.notices.find(n=>n.id===p[0]);const ph=n&&state.photos.find(ph=>ph.id===n.photo_id);const pkg=n&&state.packages.find(pkg=>pkg.id===n.package_id);const c=n&&state.customers.find(c=>c.id===n.customer_id);
   return flags.photoOwnership&&n&&ph&&pkg&&c&&n.company_id===p[1]&&n.package_id===p[2]&&n.customer_id===p[3]&&n.facility_id===p[4]&&n.event_type===p[5]&&n.fingerprint===p[6]&&ph.kind===p[7]&&c.email===p[8]&&c.contact_revision===p[9]&&String(pkg.tracking_number||'')===p[10]&&ph.company_id===n.company_id&&ph.package_id===n.package_id&&ph.facility_id===n.facility_id&&pkg.customer_id===n.customer_id&&pkg.company_id===n.company_id&&c.company_id===n.company_id&&ph.storage_path===n.photo_path&&ph.mime_type===n.photo_mime?row({id:n.id}):[];
  }
  if(q.startsWith('select stage,current_location_id from parcel_snap.packages'))return row(state.packages.find(x=>x.id===p[0]&&x.company_id===p[1]));
  if(q.startsWith('select * from parcel_snap.packages'))return row(state.packages.find(x=>x.id===p[0]));
  if(q.startsWith('select * from parcel_snap.arrival_notices'))return row(state.notices.find(x=>x.company_id===p[0]&&x.package_id===p[1]&&x.event_type===p[2]));
  if(q.startsWith('select ')&&q.includes('from parcel_snap.customers'))return row(state.customers.find(x=>x.id===p[0]&&x.company_id===p[1]));
  if(q.startsWith('select ')&&q.includes('from parcel_snap.facilities'))return row(state.facilities.find(x=>x.id===p[0]&&x.company_id===p[1]&&x.active));
  if(q.startsWith('select ')&&q.includes('from parcel_snap.company_profiles'))return row(state.profile);
  if(q.startsWith('select ')&&q.includes('from parcel_snap.companies'))return [{name:'Synthetic Shipping'}];
  if(q.startsWith('select status,provider_message_id'))return row(state.legacy.find(x=>x.package_id===p[0]&&x.event_type===p[1]));
  if(q.startsWith('select parcel_snap.assign_suggested_location')){const pkg=state.packages.find(x=>x.id===p[0]);if(flags.assignStage&&pkg){pkg.stage=flags.assignStage;pkg.current_location_id=id(88);}return [{location_id:pkg?.current_location_id||null}];}
  if(q.startsWith('insert into parcel_snap.packages')){const x={id:p[0],company_id:p[1],customer_id:p[2],tracking_number:p[3],carrier:p[4],size_class:p[5],weight_lb:p[6],payment_status:p[7],ocr_name:p[10],ocr_raw_text:p[11],ocr_recipient_address:p[12],stage:'ORIGIN_RECEIVED',origin_facility_id:p[8],destination_facility_id:p[9],current_facility_id:p[8]};state.packages.push(x);return row(x);}
  if(q.startsWith('insert into parcel_snap.package_photos')){const x={id:id(sequence++),company_id:p[0],package_id:p[1],facility_id:p[2],kind:p[3],storage_path:p[4],mime_type:p[5]};state.photos.push(x);return row(x);}
  if(q.startsWith('insert into parcel_snap.package_events')){state.events.push(copy(p));return [];}
  if(q.startsWith('insert into parcel_snap.arrival_notices')){
   if(flags.prepareFailure)throw Error('Synthetic database prepare failure');
   const x={id:id(sequence++),company_id:p[0],package_id:p[1],customer_id:p[2],facility_id:p[3],event_type:p[4],photo_id:p[5],photo_path:p[6],photo_mime:p[7],photo_sha256:p[8],fingerprint:p[9],payload:JSON.parse(p[10]),status:p[11],provider_message_id:p[12],error_message:p[13],attempt_count:0,claim_token:null};state.notices.push(x);return row(x);
  }
  if(q.startsWith('update parcel_snap.packages set source_photo_url')){const x=state.packages.find(x=>x.id===p[1]&&x.company_id===p[2]);if(x)x.source_photo_url=p[0];return [];}
  if(q.startsWith('update parcel_snap.packages set destination_facility_id')){const x=state.packages.find(x=>x.id===p[1]&&x.company_id===p[2]);if(x)Object.assign(x,{destination_facility_id:p[0],current_facility_id:p[0],stage:'DESTINATION_RECEIVED'});return [];}
  if(q.startsWith('update parcel_snap.packages set customer_id')){const x=state.packages.find(x=>x.id===p[3]&&x.company_id===p[4]);if(x)Object.assign(x,{customer_id:p[0],tracking_number:p[1],destination_facility_id:p[2]});return [];}
  if(q.startsWith('update parcel_snap.packages set carrier')){const x=state.packages.find(x=>x.id===p[7]&&x.company_id===p[8]);if(x)Object.assign(x,{carrier:p[0],size_class:p[1],weight_lb:p[2],payment_status:p[3],ocr_name:p[4],ocr_raw_text:p[5],ocr_recipient_address:p[6]});return row(x);}
  if(q.startsWith('select note from parcel_snap.package_events')){const e=[...state.events].reverse().find(x=>x[0]===p[0]&&x[1]==='DESTINATION_RECEIVED'&&[p[1],p[2]].includes(x[2]));return e?[{note:e[3]}]:[];}
  if(q.startsWith('update parcel_snap.arrival_notices set customer_id')){const x=state.notices.find(x=>x.id===p[0]&&x.status==='PENDING'&&x.attempt_count===0);if(x)Object.assign(x,{customer_id:p[1],photo_id:p[2],photo_path:p[3],photo_mime:p[4],photo_sha256:p[5],fingerprint:p[6],payload:JSON.parse(p[7])});return row(x);}
  if(q.startsWith("update parcel_snap.arrival_notices set status='sending'")){
   const x=state.notices.find(x=>x.id===p[0]&&x.fingerprint===p[3]&&['PENDING','FAILED'].includes(x.status));
   if(!x||x.status==='PENDING'&&x.attempt_count!==0||!state.profile.needs_customer_notifications||!state.profile.notification_channels.includes('EMAIL')||state.customers.find(c=>c.id===x.customer_id)?.email!==x.payload.to[0]||state.customers.find(c=>c.id===x.customer_id)?.contact_revision!==p[4]||!state.packages.some(pkg=>pkg.id===x.package_id&&pkg.company_id===x.company_id&&pkg.customer_id===x.customer_id&&String(pkg.tracking_number||'')===p[5]))return [];
   Object.assign(x,{status:'SENDING',claim_token:p[1],confirmed_by:p[2],attempt_count:x.attempt_count+1});return row(x);
  }
  if(q.startsWith('update parcel_snap.arrival_notices set status=$2')){
   if(flags.finishFailures>0){flags.finishFailures--;throw Error('Synthetic persistence failure');}
   const x=state.notices.find(x=>x.id===p[0]&&(x.claim_token||null)===(p[5]||null));if(x)Object.assign(x,{status:p[1],provider_message_id:p[2]||x.provider_message_id,error_message:p[3],provider_event:p[4]});return row(x&&{id:x.id});
  }
  throw Error('Unmocked SQL: '+query);
 }
 const sql={unsafe,async begin(fn){const previous=queue;let release;queue=new Promise(r=>release=r);await previous;const snapshot=copy(state);try{return await fn({unsafe});}catch(e){Object.assign(state,snapshot);throw e;}finally{release();}}};
 const storage={async upload(path,bytes){if(flags.uploadError)return {error:Error('Synthetic upload failure')};if(objects.has(path))return {error:Error('Already exists')};objects.set(path,Buffer.from(bytes));return {error:null};},async download(path){if(flags.downloadError||!objects.has(path))return {error:Error('Missing')};const bytes=flags.corruptDownload?Buffer.from('bad'):objects.get(path);return {data:new Blob([bytes]),error:null};}};
 const fetch=async(url,init={})=>{calls.push({url,...init});if(flags.providerDelay)await new Promise(r=>setTimeout(r,flags.providerDelay));if(flags.providerThrow)throw Error('Synthetic timeout');if(!init.method){const n=state.notices[0];return new Response(JSON.stringify({id:n.provider_message_id,...n.payload,last_event:'delivered'}));}return new Response(flags.malformed?'not-json':JSON.stringify(flags.providerStatus===200?{id:'provider-test-id'}:{message:'Synthetic rejection'}),{status:flags.providerStatus});};
 const deps={repo:createArrivalRepository(sql),storage,assertPrivateStorage:async()=>{if(!flags.privateBucket)throw Error('Private storage required');},secret:async()=>flags.secret?'synthetic-only-key':'',fetch,canOperate:async()=>flags.allowOperate};
 const input={companyId:ids.company,userId:ids.user,role:'OWNER',actor:'owner@example.test',kind:'origin',body:{intake_package_id:ids.package,customer_id:ids.customer,origin_facility_id:ids.origin,destination_facility_id:ids.destination,tracking_number:'0012345678901234567890',photo_data_url:dataUrl,label_confirmed:true,confirmed_customer_id:ids.customer,confirmed_customer_contact_version:contactVersion}};
 return {state,flags,objects,calls,queries,sql,deps,input,run:()=>processArrival(input,deps)};
}

test('confirmed photo → durable parcel/event → captured email carries exact private bytes, recipient and leading-zero tracking',async()=>{
 const h=harness(),r=await h.run();assert.equal(r.email.status,'SENT');assert.equal(r.photo_saved,true);assert.equal(h.state.packages.length,1);assert.equal(h.state.photos.length,1);assert.equal(h.state.notices.length,1);assert.equal(h.state.events.length,1);
 const mail=JSON.parse(h.calls[0].body);assert.deepEqual(mail.to,['recipient@example.test']);assert(mail.text.includes(h.input.body.tracking_number));assert.equal(mail.attachments.length,1);assert.deepEqual(Buffer.from(mail.attachments[0].content,'base64'),image);assert.equal(mail.attachments[0].filename,'parcel-label.jpg');assert(!mail.attachments[0].path);assert(!JSON.stringify(mail).includes('supabase'));assert.equal(h.state.notices[0].status,'SENT');
});
test('explicit confirmation is required even when OCR claims certainty',async()=>{const h=harness();h.input.body.label_confirmed=false;h.input.body.ocr_confidence=1;const r=await h.run();assert.equal(r.email.status,'REVIEW_REQUIRED');assert.equal(h.calls.length,0);assert.equal(h.state.notices[0].attempt_count,0);});
test('confirmation for a different customer cannot authorize sending',async()=>{const h=harness();h.input.body.confirmed_customer_id=id(99);assert.equal((await h.run()).email.status,'REVIEW_REQUIRED');assert.equal(h.calls.length,0);});
test('same intake can be reviewed and sent later without a second parcel',async()=>{const h=harness();h.input.body.label_confirmed=false;await h.run();h.input.body.label_confirmed=true;assert.equal((await h.run()).email.status,'SENT');assert.equal(h.state.packages.length,1);assert.equal(h.calls.length,1);});
test('unattempted review-only draft allows corrected customer/tracking/photo under same ID',async()=>{const h=harness();h.input.body.label_confirmed=false;await h.run();const c={id:id(22),company_id:ids.company,name:'Corrected Recipient',email:'corrected@example.test',contact_revision:'seed-1'};h.state.customers.push(c);h.input.body.customer_id=c.id;h.input.body.confirmed_customer_id=c.id;h.input.body.confirmed_customer_contact_version=correctedContactVersion;h.input.body.tracking_number='009999999999';h.input.body.label_confirmed=true;const r=await h.run();assert.equal(r.email.status,'SENT');assert.equal(h.state.packages.length,1);assert.equal(h.state.packages[0].customer_id,c.id);assert.deepEqual(JSON.parse(h.calls[0].body).to,[c.email]);});
test('sent event rejects changed photo/tracking and never resends',async()=>{const h=harness();await h.run();h.input.body.tracking_number='other';await assert.rejects(h.run,/different label details/);assert.equal(h.calls.length,1);});
test('durable accepted event suppresses duplicates across a new repository instance',async()=>{const h=harness();await h.run();h.deps.repo=createArrivalRepository(h.sql);const r=await h.run();assert.equal(r.email.status,'SENT');assert.equal(r.email.duplicate,true);assert.equal(h.calls.length,1);assert.equal(h.state.events.length,1);});
test('concurrent identical intake is one parcel/event and one provider POST',async()=>{const h=harness();h.flags.providerDelay=20;const results=await Promise.all([h.run(),h.run(),h.run()]);assert.equal(h.calls.length,1);assert.equal(h.state.packages.length,1);assert.equal(h.state.events.length,1);assert(results.some(r=>r.email.status==='SENT'));});
test('storage failure makes no DB changes or sends; same-ID retry succeeds',async()=>{const h=harness();h.flags.uploadError=true;await assert.rejects(h.run,/Photo upload failed/);assert.equal(h.state.packages.length,0);assert.equal(h.calls.length,0);h.flags.uploadError=false;assert.equal((await h.run()).email.status,'SENT');});
test('DB preparation rollback leaves only private retryable object, not partial parcel/email',async()=>{const h=harness();h.flags.prepareFailure=true;await assert.rejects(h.run,/prepare failure/);assert.equal(h.state.packages.length,0);assert.equal(h.state.photos.length,0);assert.equal(h.calls.length,0);assert.equal(h.objects.size,1);h.flags.prepareFailure=false;assert.equal((await h.run()).email.status,'SENT');assert.equal(h.objects.size,1);});
test('private photo corruption prevents sending',async()=>{const h=harness();h.flags.corruptDownload=true;await assert.rejects(h.run,/integrity/);assert.equal(h.calls.length,0);});
test('joined company/package/customer/facility/photo check is required immediately before attachment',async()=>{const h=harness();h.flags.photoOwnership=false;const r=await h.run();assert.equal(r.email.status,'FAILED');assert.match(r.email.error,/ownership/);assert.equal(h.calls.length,0);});
test('foreign-tenant customer or package is rejected before storage write',async()=>{for(const type of ['customer','package']){const h=harness();if(type==='customer')h.state.customers[0].company_id=id(99);else h.state.packages.push({id:ids.package,company_id:id(99)});await assert.rejects(h.run,/not found/);assert.equal(h.objects.size,0);assert.equal(h.calls.length,0);}});
test('foreign destination or missing facility operation permission is rejected',async()=>{const h=harness();h.state.facilities[1].company_id=id(99);await assert.rejects(h.run,/Destination warehouse/);assert.equal(h.objects.size,0);const g=harness();g.flags.allowOperate=false;await assert.rejects(g.run,/not assigned/);assert.equal(g.objects.size,0);});
test('client-supplied recipient/path cannot override server-bound email or attachment',async()=>{const h=harness();Object.assign(h.input.body,{customer_email:'intruder@example.test',photo_path:'foreign/photo.jpg'});await h.run();assert.deepEqual(JSON.parse(h.calls[0].body).to,['recipient@example.test']);assert.deepEqual(Buffer.from(JSON.parse(h.calls[0].body).attachments[0].content,'base64'),image);});
test('preferences and missing recipient block origin sends',async()=>{for(const type of ['disabled','channel','email']){const h=harness();if(type==='disabled')h.state.profile.needs_customer_notifications=false;if(type==='channel')h.state.profile.notification_channels=['SMS'];if(type==='email'){h.state.customers[0].email=null;h.input.body.confirmed_customer_contact_version=await customerContactVersion(ids.company,h.state.customers[0]);}assert(['DISABLED','EMAIL_NOT_LISTED'].includes((await h.run()).email.status));assert.equal(h.calls.length,0);}});
test('destination uses stored customer/tracking; honors preferences and dedupes repetitions',async()=>{const h=harness();await h.run();h.input.kind='destination';h.input.body={package_id:ids.package,facility_id:ids.destination,photo_data_url:dataUrl,label_confirmed:true,confirmed_customer_id:ids.customer,confirmed_customer_contact_version:contactVersion,customer_id:id(99),tracking_number:'ATTACK'};h.input.body.confirmed_package_review_version=await packageReviewVersion(ids.company,h.state.packages.find(p=>p.id===h.input.body.package_id));h.state.profile.needs_customer_notifications=false;assert.equal((await h.run()).email.status,'DISABLED');assert.equal(h.calls.length,1);h.state.profile.needs_customer_notifications=true;assert.equal((await h.run()).email.status,'SENT');await h.run();assert.equal(h.calls.length,2);assert(JSON.parse(h.calls[1].body).text.includes('0012345678901234567890'));assert(!JSON.parse(h.calls[1].body).text.includes('ATTACK'));});
test('missing schema is fail-closed before writes and missing email config is safe to retry',async()=>{const h=harness();h.flags.schema=false;await assert.rejects(h.run,/schema is not installed/);assert.equal(h.objects.size,0);const g=harness();g.flags.secret=false;const r=await g.run();assert.equal(r.email.status,'FAILED');assert.equal(r.email.retryable,true);assert.equal(g.calls.length,0);g.flags.secret=true;assert.equal((await g.run()).email.status,'SENT');});
test('documented provider rejection permits explicit same-payload retry',async()=>{const h=harness();h.flags.providerStatus=429;assert.equal((await h.run()).email.status,'FAILED');h.flags.providerStatus=200;assert.equal((await h.run()).email.status,'SENT');assert.equal(h.calls.length,2);assert.equal(h.calls[0].body,h.calls[1].body);assert.equal(h.calls[0].headers['Idempotency-Key'],h.calls[1].headers['Idempotency-Key']);});
test('timeout, 5xx, 409, malformed success remain UNKNOWN and never auto-retry',async()=>{for(const type of ['timeout','500','409','malformed']){const h=harness();if(type==='timeout')h.flags.providerThrow=true;else if(type==='malformed')h.flags.malformed=true;else h.flags.providerStatus=Number(type);assert.equal((await h.run()).email.status,'UNKNOWN');h.flags.providerThrow=false;h.flags.providerStatus=200;h.flags.malformed=false;h.deps.repo=createArrivalRepository(h.sql);assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.calls.length,1);}});
test('accepted response plus failed ledger write retains UNKNOWN provider ID for GET-only reconciliation',async()=>{const h=harness();h.flags.finishFailures=1;assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.state.notices[0].provider_message_id,'provider-test-id');h.input.body.reconcile_notification=true;const r=await h.run();assert.equal(r.email.status,'SENT');assert.equal(r.email.reconciled,true);assert.equal(h.calls.length,2);assert.equal(h.calls[1].method,undefined);assert.equal(h.calls.filter(x=>x.method==='POST').length,1);});
test('lost response without provider ID stays blocked even when reconciliation requested',async()=>{const h=harness();h.flags.providerThrow=true;await h.run();h.flags.providerThrow=false;h.input.body.reconcile_notification=true;assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.calls.length,1);});
test('provider reconciliation mismatch stays UNKNOWN with no POST',async()=>{const h=harness();h.flags.finishFailures=1;await h.run();h.input.body.reconcile_notification=true;h.deps.fetch=async()=>new Response(JSON.stringify({id:'wrong',to:['other@example.test']}));assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.calls.length,1);});
test('crash after acceptance and repeated status-write failures preserves durable SENDING no-resend barrier',async()=>{const h=harness();h.flags.finishFailures=2;assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.state.notices[0].status,'SENDING');assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.calls.length,1);});
test('legacy accepted origin is never resent by upgraded workflow',async()=>{const h=harness();h.state.packages.push({id:ids.package,company_id:ids.company,customer_id:ids.customer,origin_facility_id:ids.origin,destination_facility_id:ids.destination,tracking_number:h.input.body.tracking_number,stage:'ORIGIN_RECEIVED'});h.state.legacy.push({package_id:ids.package,event_type:'ORIGIN_ARRIVAL',status:'SENT',provider_message_id:'legacy-id'});assert.equal((await h.run()).email.status,'SENT');assert.equal(h.calls.length,0);});
test('legacy partial origin cannot be mistaken for a safe new email',async()=>{const h=harness();h.state.packages.push({id:ids.package,company_id:ids.company,customer_id:ids.customer,origin_facility_id:ids.origin,destination_facility_id:ids.destination,tracking_number:h.input.body.tracking_number,stage:'ORIGIN_RECEIVED'});assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.calls.length,0);});
test('photo type and size checks reject nonimage and mismatched content',async()=>{await assert.rejects(()=>validatePhoto('data:image/jpeg;base64,'+Buffer.from('not-image').toString('base64')),/content/);await assert.rejects(()=>validatePhoto(dataUrl.replace('image/jpeg','image/png')),/content/);await assert.rejects(()=>validatePhoto('data:text/html;base64,SGVsbG8='),/JPEG/);});
test('SQL proposal and adapter contain durable scoped constraints, locks, immutable claims, and private access',()=>{const schema=fs.readFileSync(new URL('../backend/schema-proposals/arrival-notices.sql',import.meta.url),'utf8');assert.match(schema,/unique\(company_id,package_id,event_type\)/);assert.match(schema,/foreign key\(photo_id,company_id,package_id,facility_id\)/);assert.match(schema,/enable row level security/);assert.match(schema,/revoke all.*from public,anon,authenticated/);const source=fs.readFileSync(new URL('../backend/arrival-workflow.mjs',import.meta.url),'utf8');assert.match(source,/pg_advisory_xact_lock/);assert.match(source,/for update/);assert.match(source,/fingerprint=\$4 and status in \('PENDING','FAILED'\)/);assert.match(source,/claim_token is not distinct from/);assert(!source.includes('createSignedUrl'));});

test('public or unverified photo bucket blocks all storage/database/mail writes',async()=>{const h=harness();h.flags.privateBucket=false;await assert.rejects(h.run,/Private storage required/);assert.equal(h.objects.size,0);assert.equal(h.state.packages.length,0);assert.equal(h.calls.length,0);});

test('legacy destination after package moves away remains UNKNOWN based on historical exact-facility photo',async()=>{const h=harness();h.state.packages.push({id:ids.package,company_id:ids.company,customer_id:ids.customer,origin_facility_id:ids.origin,current_facility_id:ids.origin,tracking_number:'OLD123',stage:'IN_TRANSIT'});h.state.photos.push({id:id(90),company_id:ids.company,package_id:ids.package,facility_id:ids.destination,kind:'DESTINATION',storage_path:'legacy/private.jpg'});h.input.kind='destination';h.input.body={package_id:ids.package,facility_id:ids.destination,photo_data_url:dataUrl,label_confirmed:true,confirmed_customer_id:ids.customer,confirmed_customer_contact_version:contactVersion};h.input.body.confirmed_package_review_version=await packageReviewVersion(ids.company,h.state.packages.find(p=>p.id===h.input.body.package_id));assert.equal((await h.run()).email.status,'UNKNOWN');assert.equal(h.calls.length,0);});
test('GET-only reconcile survives changed email and absent client photo without another upload or send',async()=>{const h=harness();h.flags.finishFailures=1;await h.run();h.state.customers[0].email='changed@example.test';h.input.body.reconcile_notification=true;delete h.input.body.photo_data_url;const oldSize=h.objects.size;assert.equal((await h.run()).email.status,'SENT');assert.equal(h.calls.length,2);assert.equal(h.calls[1].method,undefined);assert.equal(h.objects.size,oldSize);});
test('GET-only reconcile rejects foreign company, wrong facility and denied operation without provider access',async()=>{
 for(const scope of ['company','facility','permission']){
  const h=harness();h.flags.finishFailures=1;await h.run();h.input.body.reconcile_notification=true;delete h.input.body.photo_data_url;
  if(scope==='company')h.input.companyId=id(99);if(scope==='facility')h.input.body.origin_facility_id=ids.destination;if(scope==='permission')h.flags.allowOperate=false;
  await assert.rejects(h.run,/not found|not assigned/);assert.equal(h.calls.length,1);
 }
});

test('arrival response returns final persisted stage/location after warehouse assignment',async()=>{const h=harness();await h.run();h.flags.assignStage='WAREHOUSED';h.input.kind='destination';h.input.body={package_id:ids.package,facility_id:ids.destination,photo_data_url:dataUrl,label_confirmed:true,confirmed_customer_id:ids.customer,confirmed_customer_contact_version:contactVersion};h.input.body.confirmed_package_review_version=await packageReviewVersion(ids.company,h.state.packages.find(p=>p.id===h.input.body.package_id));const r=await h.run();assert.equal(r.stage,'WAREHOUSED');assert.equal(r.assigned_location_id,id(88));assert.equal(r.stage,h.state.packages[0].stage);});

test('same-fingerprint pending draft persists corrected metadata before confirmation',async()=>{const h=harness();h.input.body.label_confirmed=false;await h.run();const fp=h.state.notices[0].fingerprint;Object.assign(h.input.body,{ocr_recipient_address:'124 Corrected Way, Unit 009, Miami FL 33101',ocr_name:'Reviewed Recipient',ocr_raw_text:'Reviewed label',carrier:'UPS',size_class:'SMALL',weight_lb:'2.50',payment_status:'PAID',label_confirmed:true});assert.equal((await h.run()).email.status,'SENT');assert.equal(h.state.packages[0].ocr_recipient_address,h.input.body.ocr_recipient_address);assert.equal(h.state.packages[0].weight_lb,2.5);assert.equal(h.state.notices[0].fingerprint,fp);assert.equal(h.calls.length,1);});
test('attempted notice rejects metadata changes instead of silently discarding them',async()=>{const h=harness();await h.run();h.input.body.ocr_recipient_address='Changed after send';await assert.rejects(h.run,/details are frozen/);assert.equal(h.state.packages[0].ocr_recipient_address,null);assert.equal(h.calls.length,1);});
test('destination saves its initial transfer note and rejects changed same-event note',async()=>{const h=harness();await h.run();h.input.kind='destination';h.input.body={package_id:ids.package,facility_id:ids.destination,photo_data_url:dataUrl,label_confirmed:false,note:'Handle with care'};h.input.body.confirmed_package_review_version=await packageReviewVersion(ids.company,h.state.packages.find(p=>p.id===h.input.body.package_id));await h.run();assert.equal(h.state.events[1][3],'Handle with care');h.input.body.note='Edited retry';await assert.rejects(h.run,/note is already saved/);assert.equal(h.state.events.length,2);assert.equal(h.calls.length,1);});
