export function renderScanHarness(env){
 const config=JSON.stringify({url:env.SUPABASE_URL||'',key:env.SUPABASE_PUBLISHABLE_KEY||''}).replaceAll('<','\\u003c');
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Parcel Snap camera staging</title>
<style>body{font:16px system-ui;max-width:720px;margin:24px auto;padding:20px;background:#f5f7fa;color:#172436}section{background:white;padding:20px;margin:16px 0;border-radius:12px}label{display:block;margin:12px 0}input,button{font:inherit;padding:10px;box-sizing:border-box;max-width:100%}input{width:100%}img{max-width:100%;max-height:400px}pre{white-space:pre-wrap}</style>
<h1>Parcel Snap camera staging</h1><p>Scan and review only. No parcel saves, customer changes or notifications.</p><p id="health" role="status">Checking service…</p>
<section><h2>Sign in</h2><form id="login"><label>Email<input id="email" type="email" autocomplete="username" required></label><label>Password<input id="password" type="password" autocomplete="current-password" required></label><button>Sign in</button></form><button id="clear">Clear session</button><p id="auth" role="status">Use an existing authorized workspace account.</p></section>
<section><h2>Review a label</h2><p>Use fictional labels first. Customer photos require separate consent.</p><label>Take or choose photo<input id="photo" type="file" accept="image/*" capture="environment"></label><img id="image" alt="Selected test label" hidden><button id="scan" disabled>Read label</button><p id="status" role="status"></p><div id="fields"></div><pre id="metrics"></pre></section>
<script type="module">
const config=${config},$=id=>document.getElementById(id);let token='',expires=0,image='',ready=false;
try{const session=JSON.parse(sessionStorage.getItem('parcel-snap-staging-session')||'null');if(session&&session.expires>Date.now()){token=session.token;expires=session.expires;}}catch{sessionStorage.removeItem('parcel-snap-staging-session');}
const sync=()=>{$('scan').disabled=!(ready&&token&&expires>Date.now()&&image);};
const health=await fetch('/health',{cache:'no-store'}).then(r=>r.json()).catch(()=>({}));ready=Boolean(health.vision_configured&&health.auth_configured&&health.rate_limit_configured);if(token)$('auth').textContent='Signed in. Every scan verifies the active workspace role.';sync();$('health').textContent=ready?'Service configured. Accuracy requires testing.':'Scanning disabled until AI, authentication and rate limit bindings are verified.';
$('login').onsubmit=async e=>{e.preventDefault();try{if(!config.url||!config.key)throw Error('Staging authentication is not configured.');const r=await fetch(config.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});$('password').value='';const data=await r.json();if(!r.ok||!data.access_token)throw Error('Sign-in failed. Complete any required verification in the normal Parcel Snap sign-in flow.');token=data.access_token;expires=Date.now()+Number(data.expires_in||0)*1000;sessionStorage.setItem('parcel-snap-staging-session',JSON.stringify({token,expires}));$('auth').textContent='Signed in. Every scan verifies the active workspace role.';}catch(e){token='';$('password').value='';$('auth').textContent=e.message;}sync();};
$('clear').onclick=()=>{token='';expires=0;sessionStorage.removeItem('parcel-snap-staging-session');$('fields').replaceChildren();$('metrics').textContent='';$('auth').textContent='Session cleared from this page.';sync();};
$('photo').onchange=async()=>{image='';sync();$('fields').replaceChildren();$('metrics').textContent='';const file=$('photo').files[0];if(!file)return;try{const bitmap=await createImageBitmap(file),scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();image=canvas.toDataURL('image/jpeg',0.9);if(image.length>4000000)throw Error();$('image').src=image;$('image').hidden=false;$('status').textContent='Whole photo ready, without cropping.';}catch{image='';$('status').textContent='Could not prepare photo. Choose a smaller JPEG or PNG.';}sync();};
$('scan').onclick=async()=>{if(!token||expires<=Date.now()){token='';$('status').textContent='Sign in again.';sync();return;}$('scan').disabled=true;$('fields').replaceChildren();$('metrics').textContent='';const started=performance.now();$('status').textContent='Reading label…';try{const r=await fetch('/scan',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({image_data_url:image})}),data=await r.json();if(!r.ok)throw Error(data.error||'Scan failed.');for(const [name,value] of Object.entries(data.result)){if(name==='confidence')continue;const label=document.createElement('label');label.textContent=name.replaceAll('_',' ');const input=document.createElement('input');input.value=value??'';input.placeholder='Unreadable or absent — review required';label.append(input);$('fields').append(label);}$('metrics').textContent=JSON.stringify({provider:data.provider,model:data.model,model_attempts:data.model_attempts,timing_ms:data.timing_ms,browser_total_ms:Math.round(performance.now()-started)},null,2);$('status').textContent='Review every field against the photo. Confidence is not proof. Nothing was saved.';}catch(e){$('status').textContent=e.message;}finally{sync();}};
</script></html>`;
}
