// Pure configuration checks only. No client import, socket creation, network or SQL.
import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeTestConfig} from './native-test-config.mjs';
const ci=()=>({GITHUB_ACTIONS:'true',PARCEL_NATIVE_CI_DISPOSABLE:'true',PARCEL_NATIVE_PORT:'55437',PARCEL_NATIVE_DATABASE:'parcel_snap_synthetic',PARCEL_NATIVE_USER:'postgres'});
test('explicit Unix socket preserves rootless peer-test configuration',()=>{const c=nativeTestConfig({PARCEL_NATIVE_SOCKET:'/disposable/socket',USER:'synthetic-agent'});assert.equal(c.host,'/disposable/socket');assert.equal(c.username,'synthetic-agent');assert.equal(c.database,'postgres');assert.equal(c.port,55437);assert.equal(c.ssl,false);});
test('CI configuration has fixed loopback, database, user and port; no real connection is attempted',()=>{const c=nativeTestConfig(ci());assert.equal(c.host,'127.0.0.1');assert.equal(c.database,'parcel_snap_synthetic');assert.equal(c.username,'postgres');assert.equal(c.port,55437);assert.equal(c.password,'');assert.equal(c.ssl,false);});
test('missing opt-in, runtime marker or exact disposable identity is denied',()=>{for(const key of Object.keys(ci())){const e=ci();delete e[key];assert.throws(()=>nativeTestConfig(e));}for(const [key,value] of [['GITHUB_ACTIONS','false'],['PARCEL_NATIVE_CI_DISPOSABLE','false'],['PARCEL_NATIVE_PORT','5432'],['PARCEL_NATIVE_DATABASE','production'],['PARCEL_NATIVE_USER','admin'],['PARCEL_NATIVE_SOCKET','/socket']])assert.throws(()=>nativeTestConfig({...ci(),[key]:value}));});
test('arbitrary host, URL and database credential environment settings are denied',()=>{for(const key of ['PGHOST','PGPORT','PGDATABASE','PGUSER','PGPASSWORD','PGPASSFILE','PGSERVICE','PGSERVICEFILE','PGSSLMODE','DATABASE_URL','POSTGRES_URL','POSTGRES_PASSWORD','PARCEL_NATIVE_HOST','PARCEL_NATIVE_URL','PARCEL_NATIVE_PASSWORD'])assert.throws(()=>nativeTestConfig({...ci(),[key]:'synthetic-disallowed-setting'}));});
test('no default transport; malformed or nonlocal socket inputs are denied',()=>{for(const env of [{},{PARCEL_NATIVE_SOCKET:'relative/socket'},{PARCEL_NATIVE_SOCKET:'https://example.test'},{PARCEL_NATIVE_SOCKET:'/socket',PARCEL_NATIVE_PORT:'65536'},{PARCEL_NATIVE_SOCKET:'/socket',PARCEL_NATIVE_PORT:'-1'},{PARCEL_NATIVE_SOCKET:'/socket',PARCEL_NATIVE_PORT:'1e3'}])assert.throws(()=>nativeTestConfig(env));});
